# Generated by Django 5.1.2 on 2024-10-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gyeongju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', models.CharField(default='경주', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('address', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(default='thumbnails/gyeongju.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='jeju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', models.CharField(default='제주', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('address', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(default='thumbnails/jeju.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='jeonju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', models.CharField(default='전주', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('address', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(default='thumbnails/jeonju.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='yeosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', models.CharField(default='여수', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('address', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(default='thumbnails/yeosu.jpg', upload_to='')),
            ],
        ),
    ]
